PMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('manage/', admin.site.urls),
    path('', include('hospital.urls')),
    path('ai/', include('ai_ml_system.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/', include('Core.urls')),
    path('core/api/', include('API.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

patient_ms/urls.py
from django.urls import path
from patient_ms.views import (
    PatientInfoUpdate,
    DoctorAppointment,
    doctor_filter,
    DoctorPrescriptionView,
    ViewAllSavedRecord,
    PatientProfile,
    ForgetAppointmentSerialView,
    AppointmentConfirmationLetterView,
    AppointmentCopyPDFView
)

app_name = 'patient_ms'
urlpatterns = [
    path(
        'profile/',
        PatientProfile.as_view(), name='patient_profile'
    ),
    path(
        '<int:pk>/update/',
        PatientInfoUpdate.as_view(), name='patient_info_update'
    ),

    path(
        'calender/appointment/',
        DoctorAppointment.as_view(), name='appointment'
    ),
    path(
        'appointment/<int:pk>/confirmation',
        AppointmentConfirmationLetterView.as_view(),
        name='appointment_confirmation'
    ),
    path(
        'appointment/<int:pk>/download',
        AppointmentCopyPDFView.as_view(),
        name='appointment_download'
    ),

    path(
        'forget/appointment/',
        ForgetAppointmentSerialView.as_view(), name='appointment_forget'
    ),
    path('appointment/filter/', doctor_filter, name='load_doctor'),
    path(
        'patient/<int:pk>/add/record/',
        DoctorPrescriptionView.as_view(), name='add_record'
    ),
    path(
        'patient/<int:pk>/record/view/',
        ViewAllSavedRecord.as_view(), name='view_record'
    ),

]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospital.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/api/', include('core.api.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/partials/_css.html
{% load static %}

<link href="{% static 'heartcare/css/custom.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/color.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/responsive.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/prettyPhoto.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'heartcare/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
<link href="{% static 'custom/custom.css' %}" rel="stylesheet">
<link rel="icon" type="image/png" href="{% static 'image/PM.png' %}">

templates/partials/_footer.html
{% load static %}
<footer class="footer">
  <div class="footer-widgets">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <div class="widget"> <img class="ft-logo" src="{% static 'heartcare/images/logo.png' %}" alt="">
            <p>The Patient-Management-System have latest technology machines with experty Heart specialist doctors
              consectetur adipisicing elit. Distinctio vitae maiores enim ea atque? Natus iure autem cumque, quaerat
              distinctio pariatur velit illo hic a eos paccusamus. </p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3>Our Services</h3>
            <ul>
              {% for service in services|slice:':8' %}
              <li><a href="{% url 'service_details' service.id %}"><i class="fa fa-arrow-right"></i>
                  {{service.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3>Expert Doctors</h3>
            <ul>
              {% for doctor in doctors|slice:':8' %}
              <li><a href="{% url 'doctor_details' doctor.id %}"><i class="fa fa-arrow-right"></i> {{ doctor.name }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3>Contact us</h3>
            <address>
              <ul>
                <li> <span class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>Main Branch:</strong> Mirpur 2, Dhaka</span> </li>
                <li> <span class="icon"><i class="fa fa-phone-square" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>Call us Anytime at:</strong> +8801843070993</span> </li>
                <li> <span class="icon"><i class="fa fa-envelope-o" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>For Inquiry:</strong>pm-system@dkkundu.com</span> </li>
               
              </ul>
            </address>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-cr">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="footer-social"> <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a> <a href="#"><i
                class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#"><i class="fa fa-google-plus"
                aria-hidden="true"></i></a> <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a> <a
              href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
          </div>
        </div>
        <div class="col-md-6">
          <p><strong>PM-System</strong> © {% now 'Y' %}, All Rights Reserved, Design & Developed By <a class="a_tag_color" target="_blank" href="https://dkkundu.com/"> <strong>DK Kundu</strong></a> </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/_header.html
{% load static %}
{% load group_checker_tag %}
{% block style %}

{% endblock style %}
<header class="site-header">
    <div class="top-bar">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-8">
                    <ul>
                        <li><i class="fa fa-phone" aria-hidden="true"></i> Call at: <strong>+8801843070993</strong></li>
                        <li><i class="fa fa-envelope-o" aria-hidden="true"></i> Email us:
                            <strong>pm-system@dkkundu.com</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-4 top-social"><a href="#"><i class="fa fa-twitter"
                                                                         aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#"><i
                            class="fa fa-google-plus"
                            aria-hidden="true"></i></a> <a href="#"><i class="fa fa-instagram"
                                                                       aria-hidden="true"></i></a> <a
                            href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></div>
            </div>
        </div>
    </div>
    <div class="nav-logo-area">
        <div class="container ">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-default navbar-static-top">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span
                                    class="sr-only">Toggle
                  navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                                    class="icon-bar"></span></button>
                            <a class="navbar-brand logo-image" href="{% url 'index' %}"><img
                                    src="{% static 'heartcare/images/logo.png' %}"
                                    alt=""></a>
                                
                                </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'index' %}">Home</a></li>
                                </li>
                                <li><a href="{% url 'services' %}">Services</a></li>
                                <li><a href="{% url 'doctors' %}">Doctors</a></li>

                                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                                        role="button"
                                                        aria-haspopup="true" aria-expanded="false">Features <span
                                        class="fa fa-angle-down"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'gallery' %}">Gallery</a></li>
                                        <li><a href="{% url 'faqs' %}">Faqs</a></li>
                                    </ul>
                                </li>

                                <li><a href="{% url 'contact' %}">Contact</a></li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">

                                {% if user.is_authenticated %}
                                <li><a class="appoint" href="{% url 'patient_ms:appointment' %}">Appointment</a></li>

                                <li class="dropdown">
                                    <li href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-haspopup="true" aria-expanded="false">
                                        {% if login_user.picture %}
                                        <img src="{{ login_user.picture.url }}"
                                             width="40" height="40" class="rounded-circle">
                                        {% else %}
                                        <img src="{% static 'image/doctor.jpg' %}"
                                             width="40" height="40" class="rounded-circle">
                                        {% endif %}

                                    </li>
                                    <ul class="dropdown-menu">
                                        {% if user|is_doctor %}
                                            <li><a href="{% url 'doctor_dashboard' %}"> Dashboard </a></li>
                                        {% endif %}

                                        {% if user|is_patient %}
                                          <li><a href="{% url 'patient_ms:patient_profile' %}"> Profile </a></li>
                                        {% endif %}
                                        <li><a href="{% url 'logout' %}">Logout</a></li>

                                    </ul>
                                </li>
                                {% else %}
                                <li><a class="appoint" href="{% url 'login' %}">Sign In</a></li>
                                <li><a class="appoint" href="{% url 'registration_type' %}">Registration</a></li>
                                {% endif %}

                                <li><a id="menu-toggle" href="#" class="toggle"><img
                                        src="{% static 'heartcare/images/bars.png' %}"
                                        alt=""></a></li>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->


<!--                        LOG IN FORM-->


                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

templates/partials/_js.html
</div>
<!--Wrapper End-->
{% load static %}
{% load message_type_checker %}
<script src="{% static 'heartcare/js/jquery.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="{% static 'heartcare/js/bootstrap.min.js' %}"></script>
<script src="{% static 'heartcare/js/owl.carousel.min.js' %}"></script>
<!--
<script src="{% static 'heartcare/js/bootstrap-datetimepicker.min.js' %}"></script>
-->
<script src="{% static 'heartcare/js/custom.js' %}"></script>
<script src="{% static 'custom/sweetalert2.all.min.js' %}"></script>



<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'UA-108110591-1');
</script>

{% if messages %}
    {% for message in messages %}
        {% if message|message_check %}
        <script>
            Swal.fire({
              icon: 'error',
              title: 'Error...',
              text: '{{message}}',
              footer: 'Please try again'
            })

        </script>
        {% else %}
        <script>
           Swal.fire(
              'Successfully Done!',
              '{{message}}',
              'success'
            )

        </script>
        {% endif %}
    {% endfor %}
{% endif %}

<script>
    $("#division").change(function () {
    var url = $("#application_form").attr("data-district-url");
    var divisionId = $(this).val();
    $.ajax({
        url: url,
        data: {
        'division': divisionId
        },
        success: function (data) {
        $("#district").html(data);
        }
    });

});

$("#district").change(function () {
    var url = $("#application_form").attr("data-upazila-url");
    var districtId = $(this).val();
    $.ajax({
        url: url,
        data: {
        'district': districtId
        },
        success: function (data) {
        $("#upazila").html(data);
        }
    });

});

</script>

templates/partials/_pagination.html
<div class="cp-pagination">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    Prev
                </a>
            </li>
            {% endif %}

            {% for page_num in paginator.page_range|slice:":10" %}
            {% if page_obj.number == page_num %}
            <li class="active"><a href="">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    Next
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/partials/_sidebar.html
{% load static %}
<div id="sidebar-wrapper">
  <a id="menu-close" href="#" class="close toggle"><i class="fa fa-times" aria-hidden="true"></i></a>
  <ul class="sidebar-nav">
    <li class="sidebar-brand"> <a href=""><img src="{% static 'heartcare/images/footer-logo.png' %}" alt=""></a> </li>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'services' %}">Services</a></li>
    <li><a href="{% url 'doctors' %}">Doctors</a></li>
    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
        aria-expanded="false">Features <span class="fa fa-angle-down"></span></a>
      <ul class="dropdown-menu">
        <li><a href="{% url 'gallery' %}">Gallery</a></li>
        <li><a href="{% url 'faqs' %}">Faqs</a></li>
      </ul>
    </li>
    <li><a href="{% url 'contact' %}">Contacts</a></li>
  </ul>
</div>

templates/partials/_slider.html
{% load static %}
<div class="main-slider">
    <div id="main-slider" class="owl-carousel owl-theme">
      {% for slider in sliders %}
      <div class="item">
          <div class="slide-caption slide-2">
            <div class="container">
              <h1>{{ slider.caption }}</h1>
              <p>{{ slider.slogan }}</p>
              <a class="btn-1" href="#">Call for Inquiry</a> <a class="btn-1" href="#">Ask Cardiologist</a>
            </div>
          </div>
          <span class="simg"><img src="{{ slider.image.url }}" alt=""></span>
        </div>
      {% endfor %}
    </div>
  </div>