PMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('manage/', admin.site.urls),
    path('', include('hospital.urls')),
    path('ai/', include('ai_ml_system.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/', include('Core.urls')),
    path('core/api/', include('API.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

appointment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AppointmentView.as_view(), name="appointment"),
]

patient_ms/urls.py
from django.urls import path
from patient_ms.views import (
    PatientInfoUpdate,
    DoctorAppointment,
    doctor_filter,
    DoctorPrescriptionView,
    ViewAllSavedRecord,
    PatientProfile,
    ForgetAppointmentSerialView,
    AppointmentConfirmationLetterView,
    AppointmentCopyPDFView
)

app_name = 'patient_ms'
urlpatterns = [
    path(
        'profile/',
        PatientProfile.as_view(), name='patient_profile'
    ),
    path(
        '<int:pk>/update/',
        PatientInfoUpdate.as_view(), name='patient_info_update'
    ),

    path(
        'calender/appointment/',
        DoctorAppointment.as_view(), name='appointment'
    ),
    path(
        'appointment/<int:pk>/confirmation',
        AppointmentConfirmationLetterView.as_view(),
        name='appointment_confirmation'
    ),
    path(
        'appointment/<int:pk>/download',
        AppointmentCopyPDFView.as_view(),
        name='appointment_download'
    ),

    path(
        'forget/appointment/',
        ForgetAppointmentSerialView.as_view(), name='appointment_forget'
    ),
    path('appointment/filter/', doctor_filter, name='load_doctor'),
    path(
        'patient/<int:pk>/add/record/',
        DoctorPrescriptionView.as_view(), name='add_record'
    ),
    path(
        'patient/<int:pk>/record/view/',
        ViewAllSavedRecord.as_view(), name='view_record'
    ),

]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospital.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/api/', include('core.api.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.db import models
from hospital.models import Doctor
from django.utils import timezone


class Appointment(models.Model):
    time_choices = (
        ('morning', "Morning"),
        ('evening', "Evening")
    )
    name = models.CharField(max_length=120)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, related_name='appointments')
    date = models.DateField(default=timezone.now)
    time = models.CharField(choices=time_choices, max_length=10)
    note = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}-{self.doctor.name}"

appointment/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from hospital.models import Doctor
from .models import Appointment


class AppointmentView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'doctors': Doctor.objects.all()
        }
        return render(request, "appointment/index.html", context)

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        doctor_id = request.POST.get('doctor')
        date = request.POST.get('date')
        time = request.POST.get('time')
        note = request.POST.get('note')
        if doctor_id:
            doctor = get_object_or_404(Doctor, id=doctor_id)

        if(name and phone and email and doctor and date and time):
            Appointment.objects.create(
                name=name, phone=phone, email=email, doctor=doctor, date=date, time=time, note=note)
            messages.success(request,'Appointment done successfully')
        return redirect('appointment')

templates/appointment/appointement_letter.html
{% extends 'patient/profile.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block nev_block %}
<li><a href="{% url 'index' %}">Home</a></li>
<li class="active">Profile Update</li>
{%  endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'custom/re_design.css' %}"/>
<link rel="stylesheet" href="{% static 'custom/profile.css' %}"/>
<style>
  .inner-banner {
    padding: 30px 0 30px !important;
}
.card-body {
    padding: 0px 65px;
}
.card {
    width: 347px !important;
}
.container.make-box {
    margin-top: 10%;
}
.image-class_search {
    width: 78%;
}
.image-class {
    width: 66%;
}
h3.center-text {
    margin: 4px 20%;
    margin-bottom: 6%;
}


</style>
{% endblock %}

{% block profile_block %}

<div class="container make-box">
    <a class="btn btn-outline-primary" href="{% url 'patient_ms:appointment_download' pk=object.pk %}">
       <i class="fa fa-plus-square-o" aria-hidden="true"> Download</i>
    </a>
    <h3 class="center-text">Appointment Letter</h3>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3">
                <h6 class="mb-0">Doctor Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ object.doctor.name }}  ({{ object.doctor.speciality }})
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-3">
                <h6 class="mb-0">Hospital</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ object.doctor.present_hospital }}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-3">
                <h6 class="mb-0">Appointment </h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ object.appointment_day }} ( <strong> Time:</strong> {{ object.appointment_time }})
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-3">
                <h6 class="mb-0">Serial Number</h6>
            </div>
            <div class="col-sm-9 text-secondary">
                {{ object.serial_number }}
            </div>
        </div>
        <hr>

    </div>

</div>


{%  endblock %}

templates/appointment/appointment_filter.html
<option value="">---------</option>
{% for object in object_list %}
<option value="{{ object.pk }}">{{ object.name }}</option>
{% endfor %}

templates/appointment/download.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>PM_System - Appointment Copy</title>
        <link rel="stylesheet" href="{% static 'custom/profile.css' %}"/>
        <style>
            body {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
                background: #fff;
            }
            @page {
                size: "A4";
                margin: 0.5cm 1.5cm 0cm 1.5cm;
            }
            h3.center-text {
                margin: 4px 20%;
                margin-bottom: 6%;
            }

        </style>
    </head>
    <body>
        <section class="ftco-section ftco-no-pt ftc-no-pb">
            <div class="container">
                <div class="container make-box">
                <h3 class="center-text">Appointment Letter</h3>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Doctor Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ object.doctor.name }}  ({{ object.doctor.speciality }})
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Hospital</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ object.doctor.present_hospital }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Appointment </h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ object.appointment_day }} ( <strong> Time:</strong> {{ object.appointment_time }})
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Serial Number</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ object.serial_number }}
                        </div>
                    </div>
                    <hr>

                </div>

            </div>

            </div>
        </section>
    </body>
</html>

templates/appointment/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}


<style>
  .row.form-field {
    display: grid;
    grid-template-columns: 0% 50% 50%;
    grid-gap: 2px;
}
  span.asteriskField {
     color: #f00;
}
</style>
{% endblock style %}

{% block maincontent %}
<!--inner banner-->
<div class="inner-banner">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>Get Appointment</h1>
      </div>
      <div class="col-md-5">
        <ol class="breadcrumb">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li class="active">Appointment</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<!--inner banner End-->

<!--Main Content Start-->
<div class="main-content padding-0">
  <section class="appointment-form">
    <div class="container">
      <div class="row">
        <div class="col-md-6"><img src="{% static 'heartcare/images/form-pic.jpg' %}" alt=""></div>
        <div class="col-md-6">
          <form id="application_form" action="" enctype="multipart/form-data" class="form-register" method="POST" accept-charset="UTF-8"
                data-upazila-url={% url 'load_upazila' %} data-district-url={% url 'load_district' %} data-doctor-url={% url 'patient_ms:load_doctor' %}>
            {% csrf_token %}
            <div class="app-form">
                <div class="row form-field">
                    <div class="col-6">
                      {{ form.speciality|as_crispy_field }}
                    </div>
                    <div class="col-6">
                       {{ form.division|as_crispy_field }}
                    </div>
                </div>
                <div class="row form-field">
                    <div class="col-6">
                      {{ form.district|as_crispy_field }}
                    </div>
                    <div class="col-6">
                       {{ form.upazila|as_crispy_field }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                      {{ form.doctor|as_crispy_field }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                      {{ form.problem|as_crispy_field }}
                    </div>
                </div>
                  <div class="row form-field">
                    <div class="col-6">
                      {{ form.appointment_day|as_crispy_field }}
                    </div>
                    <div class="col-6">
                      {{ form.appointment_time|as_crispy_field }}
                    </div>
                </div>





              <div class="col-md-12 text-center">
                <input value="Book Appointment" type="submit">
              </div>
                <br>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>
<!--Main Content End-->
{% endblock maincontent %}


{% block extra_js %}
<script>

$('#id_appointment_day').calendar({
  type: 'date'
});

</script>
<script src="{% static 'heartcare/data_load.js' %}"></script>


{% endblock extra_js %}