PMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('manage/', admin.site.urls),
    path('', include('hospital.urls')),
    path('ai/', include('ai_ml_system.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/', include('Core.urls')),
    path('core/api/', include('API.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ai_ml_system/urls.py
"""Core > urls.py"""
# DJANGO URLS
from django.urls import path
from .views import (
    train_heart_disease_model, prediction_heart_disease,
    train_pneumonia_disease_model
)
# CORE IMPORTS
app_name = 'ai'

urlpatterns = [
    # index url ---------------------------------------------------------------
    path(
        'train-heart-disease-model/', train_heart_disease_model,
        name='train-heart-disease'
    ),
    path(
        'prediction-heart-disease/', prediction_heart_disease,
        name='prediction_heart_disease'
    ),
    path(
        'train-pneumonia-disease/', train_pneumonia_disease_model,
        name='train_pneumonia_disease'
    ),


]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospital.urls')),
    path('patient/', include('patient_ms.urls')),
    path('appointment/', include('appointment.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('django_prometheus.urls')),
    path('core/api/', include('core.api.urls')),
    path('api/', include('patient_ms.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/dashboard/prediction/type.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block title_text %}Prediction{% endblock title_text %}
{% block extra_css  %}
<style>

</style>
{% endblock extra_css %}


{% block body  %}
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

<div class="grey-bg container-fluid">
  <section id="minimal-statistics">
    <div class="row">

          <div class="col-xl-6 col-sm-6 col-12">
              <a href="{% url 'ai:prediction_heart_disease' %}">
                <div class="card">
                  <div class="card-content">
                    <div class="card-body">
                      <div class="media d-flex">
                        <div class="align-self-center">
                          <i class="icon-graph success font-large-2 float-left"></i>
                        </div>
                        <div class="media-body text-right">
                          <h3>100 % Prediction</h3>
                            <span><strong>Heart Disease</strong></span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
          </div>

      <div class="col-xl-6 col-sm-6 col-12">
           <a href="">  <div class="card">
              <div class="card-content">
                <div class="card-body">
                  <div class="media d-flex">
                    <div class="align-self-center">
                      <i class="icon-pointer danger font-large-2 float-left"></i>
                    </div>
                    <div class="media-body text-right">
                      <h3>423</h3>
                      <span>Total Visits</span>
                    </div>
                  </div>
                </div>
              </div>
            </div> </a>

      </div>
    </div>

{#    <div class="row">#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="danger">278</h3>#}
{#                  <span>New Projects</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-rocket danger font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="success">156</h3>#}
{#                  <span>New Clients</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-user success font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{##}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="warning">64.89 %</h3>#}
{#                  <span>Conversion Rate</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-pie-chart warning font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="primary">423</h3>#}
{#                  <span>Support Tickets</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-support primary font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{##}
{#    <div class="row">#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="primary">278</h3>#}
{#                  <span>New Posts</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-book-open primary font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#              <div class="progress mt-1 mb-0" style="height: 7px;">#}
{#                <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="warning">156</h3>#}
{#                  <span>New Comments</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-bubbles warning font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#              <div class="progress mt-1 mb-0" style="height: 7px;">#}
{#                <div class="progress-bar bg-warning" role="progressbar" style="width: 35%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{##}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="success">64.89 %</h3>#}
{#                  <span>Bounce Rate</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-cup success font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#              <div class="progress mt-1 mb-0" style="height: 7px;">#}
{#                <div class="progress-bar bg-success" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="col-xl-3 col-sm-6 col-12">#}
{#        <div class="card">#}
{#          <div class="card-content">#}
{#            <div class="card-body">#}
{#              <div class="media d-flex">#}
{#                <div class="media-body text-left">#}
{#                  <h3 class="danger">423</h3>#}
{#                  <span>Total Visits</span>#}
{#                </div>#}
{#                <div class="align-self-center">#}
{#                  <i class="icon-direction danger font-large-2 float-right"></i>#}
{#                </div>#}
{#              </div>#}
{#              <div class="progress mt-1 mb-0" style="height: 7px;">#}
{#                <div class="progress-bar bg-danger" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
  </section>


</div>
{% endblock %}